# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('caption', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('hls_manifest_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reels/source/')),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_shareable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_awards', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommendation_score', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='content.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='creators.creatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reels_reel_status_98ffd2_idx'), models.Index(fields=['status', 'recommendation_score'], name='reels_reel_status_dd4a4e_idx'), models.Index(fields=['creator', 'status'], name='reels_reel_creator_974bfd_idx')],
            },
        ),
    ]
