# Generated by Django 5.2.15 on 2026-07-02 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=180)),
                ('content_focus', models.CharField(blank=True, max_length=220)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('payout_phone', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=80)),
                ('total_followers', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('total_likes', models.PositiveBigIntegerField(default=0)),
                ('total_votes', models.PositiveBigIntegerField(default=0)),
                ('total_awards', models.PositiveBigIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
