services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A umbrella_backend worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: umbrella_db
      POSTGRES_USER: umbrella_user
      POSTGRES_PASSWORD: umbrella_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
