# Generated by Django 5.2.15 on 2026-07-02 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('licenses', 'Licenses'), ('help', 'Help Center')], max_length=30)),
                ('body', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page_type', 'title'],
            },
        ),
    ]
