# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('seconds_watched', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_valid_view', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
