# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchsession',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_sessions', to='creators.creatorprofile'),
        ),
    ]
