# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['creator', 'target_type', 'started_at'], name='analytics_w_creator_319728_idx'),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['user', 'target_type', 'started_at'], name='analytics_w_user_id_b8a64b_idx'),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['is_valid_view', 'started_at'], name='analytics_w_is_vali_737f2e_idx'),
        ),
    ]
