# Generated by Django 5.2.15 on 2026-07-02 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=180)),
                ('content_type', models.CharField(max_length=160)),
                ('portfolio_url', models.URLField(blank=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='creator_applications/id_documents/')),
                ('message', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
