# Generated by Django 5.2.15 on 2026-07-02 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('text', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('points', models.PositiveIntegerField(default=1)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to='creators.creatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
