# Generated by Django 5.2.15 on 2026-07-02 19:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name=datetime.datetime(2026, 8, 1, 19, 32, 24, 577144, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('local_asset_key', models.CharField(blank=True, max_length=240)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_licenses', to='content.content')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
