# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('image_url', models.URLField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='home/banners/')),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel'), ('external', 'External Link')], default='content', max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='content.content')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='reels.reel')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('section_kind', models.CharField(choices=[('featured', 'Featured'), ('new_arrivals', 'New Arrivals'), ('popular', 'Popular'), ('trending', 'Trending'), ('recommended', 'Recommended'), ('continue_watching', 'Continue Watching'), ('category', 'Category')], max_length=40)),
                ('content_type', models.CharField(blank=True, max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item_limit', models.PositiveIntegerField(default=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
