# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default reward formula', max_length=120)),
                ('platform_share_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('creator_pool_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('watch_time_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('valid_views_weight', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('engagement_weight', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('votes_weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('awards_weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatorEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_revenue_pool_tzs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creator_score', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount_tzs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('held', 'Held')], default='pending', max_length=20)),
                ('calculation_notes', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='creators.creatorprofile')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('creator', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='creators.creatorprofile')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='rewards.creatorearning')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
