# Generated by Django 5.2.15 on 2026-07-02 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hide', 'Hide'), ('restore', 'Restore'), ('suspend_creator', 'Suspend Creator'), ('takedown', 'Takedown')], max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('reel', 'Reel')], max_length=20)),
                ('target_id', models.UUIDField(default=uuid.uuid4)),
                ('reason', models.CharField(choices=[('copyright', 'Copyright'), ('harmful', 'Harmful Content'), ('hate', 'Hate or Harassment'), ('sexual', 'Sexual Content'), ('spam', 'Spam or Scam'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
