# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('content_transcode', 'Content Transcode'), ('reel_transcode', 'Reel Transcode'), ('thumbnail', 'Thumbnail')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('output_hls_url', models.URLField(blank=True)),
                ('output_mp4_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reels.reel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
