# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file_url', models.URLField(blank=True)),
                ('hls_manifest_url', models.URLField(blank=True)),
                ('dash_manifest_url', models.URLField(blank=True)),
                ('mp4_url', models.URLField(blank=True)),
                ('local_hls_path', models.CharField(blank=True, max_length=500)),
                ('quality_label', models.CharField(default='720p', max_length=30)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('drm_license_url', models.URLField(blank=True)),
                ('watermark_text', models.CharField(blank=True, max_length=120)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'TV Series'), ('documentary', 'Documentary'), ('educational', 'Educational'), ('sport', 'Sports'), ('kids', 'Kids'), ('news', 'News'), ('premium_creator', 'Premium Creator Content'), ('other', 'Other')], max_length=30)),
                ('language', models.CharField(default='Swahili', max_length=50)),
                ('age_rating', models.CharField(default='General', max_length=20)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('banner_image_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='content/thumbnails/')),
                ('banner_file', models.ImageField(blank=True, null=True, upload_to='content/banners/')),
                ('source_video_file', models.FileField(blank=True, null=True, upload_to='content/source/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=True)),
                ('early_access', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_awards', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommendation_score', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
