# Generated by Django 5.2.15 on 2026-07-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='creators.creatorprofile'),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_asset', to='content.content'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'content_type', 'created_at'], name='content_con_status_9768fb_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'is_featured', 'created_at'], name='content_con_status_834ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'is_trending', 'recommendation_score'], name='content_con_status_6dab24_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['creator', 'status'], name='content_con_creator_3d8451_idx'),
        ),
    ]
