# Generated by Django 5.2.15 on 2026-07-02 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('system', 'System'), ('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=10)),
                ('autoplay_reels', models.BooleanField(default=True)),
                ('download_quality', models.CharField(default='720p', max_length=20)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
